import cv2

FRAME_QUEUE_SIZE = 40
FRAME_HEIGHT = 3036
FRAME_WIDTH = 4024
DISPLAY_WIDTH = 780
DISPLAY_HEIGHT = 780
NUM_DETECTOR_THREADS = 6

DETECTION_FRAME_SKIP = 2 
DETECTION_DOWNSCALE = 2  

cv2.setUseOptimized(True)
